# name: books
services:

  app:
    build: .
    image: finkord/books-api:lab3-a_e4d0541
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    networks:
      - books_network

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/psql:/var/lib/postgresql/data
      - ./configs/psql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d booksdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - books_network

networks:
  books_network:
    driver: bridge
